<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <EnableLibraryImportGenerator>true</EnableLibraryImportGenerator>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ApplicationIcon>hasc-icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.3.0" />
    <PackageReference Include="System.Speech" Version="10.0.6" />
  </ItemGroup>

</Project>