using System.Runtime.InteropServices;

namespace HASCore.Keyboard;

/// <summary>
///     Provides methods for emulating keyboard input at the system level.
/// </summary>
/// <remarks>
///     This class uses the Windows <c>SendInput</c> API to inject keyboard events
///     as if they were generated by a physical keyboard. It supports sending
///     individual key presses or releases using scan codes to avoid issues with
///     extended keys (e.g., right Alt, right Ctrl).
/// </remarks>
public static class KeyboardEmulator
{
    #region WinAPI Constants and Imports

    // Input type for keyboard events.
    private const Int32     INPUT_KEYBOARD      = 1;
    // Flags for keyboard event.
    private const UInt32    KEYEVENTF_KEYDOWN   = 0x0000;
    private const UInt32    KEYEVENTF_KEYUP     = 0x0002;
    private const UInt32    KEYEVENTF_SCANCODE  = 0x0008;
    // Translation type for MapVirtualKey.
    private const UInt32    MAPVK_VK_TO_VSC     = 0x00;

    /// <summary>
    ///     Synthesizes keystrokes, mouse motions, and button clicks.
    /// </summary>
    /// <remarks>
    ///     The <c>SendInput</c> function inserts input events into the same thread's
    ///     input queue. This function is the primary method for generating
    ///     synthetic keyboard input.
    /// </remarks>
    /// <param name="nInputs">
    ///     The number of structures in the <paramref name="pInputs"/> array.
    /// </param>
    /// <param name="pInputs">
    ///     An array of <see cref="INPUT"/> structures. Each structure represents
    ///     an input event (keyboard, mouse, or hardware).
    /// </param>
    /// <param name="cbSize">
    ///     The size, in bytes, of an <see cref="INPUT"/> structure.
    /// </param>
    /// <returns>
    ///     The number of events that were successfully inserted into the input queue.
    ///     If the function returns zero, the input was blocked by another thread.
    ///     To get extended error information, call <see cref="Marshal.GetLastWin32Error"/>.
    /// </returns>
    [DllImport("user32.dll", SetLastError = true)]
    private static extern UInt32 SendInput(UInt32 nInputs, INPUT[] pInputs, Int32 cbSize);

    /// <summary>
    ///     Retrieves the extra message information for the current thread.
    /// </summary>
    /// <remarks>
    ///     This function is used to get the extra information that was associated
    ///     with the current input message. It is typically used with <c>SendInput</c>
    ///     to pass application-defined data.
    /// </remarks>
    /// <returns>
    ///     The extra message information as an <see cref="IntPtr"/>.
    /// </returns>
    [DllImport("user32.dll")]
    private static extern IntPtr GetMessageExtraInfo();

    /// <summary>
    ///     Translates a virtual‑key code into a scan code or character value.
    /// </summary>
    /// <remarks>
    ///     This function is used to obtain the hardware scan code corresponding
    ///     to a given virtual key, which is necessary when using scan‑code
    ///     based keyboard input via <c>SendInput</c>.
    /// </remarks>
    /// <param name="uCode">
    ///     The virtual‑key code to translate.
    /// </param>
    /// <param name="uMapType">
    ///     The translation to perform. Must be <c>MAPVK_VK_TO_VSC</c> (0x00)
    ///     to convert a virtual key to a scan code.
    /// </param>
    /// <returns>
    ///     The scan code corresponding to the specified virtual key.
    /// </returns>
    [DllImport("user32.dll")]
    private static extern UInt32 MapVirtualKey(UInt32 uCode, UInt32 uMapType);

    #endregion

    #region Private Structures

    /// <summary>
    ///     Structure representing a keyboard input event.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    private struct KEYBDINPUT
    {
        public UInt16 wVk;          // Virtual‑key code (0 if using scan code).
        public UInt16 wScan;        // Hardware scan code.
        public UInt32 dwFlags;      // Flags (key down/up, scancode flag, etc.).
        public UInt32 time;         // Timestamp (0 = system provides).
        public IntPtr dwExtraInfo;  // Additional application‑defined data.
    }

    /// <summary>
    ///     Structure for a generic input event (keyboard, mouse, or hardware).
    /// </summary>
    private struct INPUT
    {
        public Int32 type;          // Type of input (INPUT_KEYBOARD, etc.).
        public KEYBDINPUT ki;       // Keyboard input data.
    }

    #endregion

    #region Public Methods

    /// <summary>
    ///     Emulates a single key press or release.
    /// </summary>
    /// <param name="key">The virtual key to send (from the <see cref="Keys"/> enumeration).</param>
    /// <param name="keyDown">
    ///     <c>true</c> to simulate a key down (press) event;
    ///     <c>false</c> to simulate a key up (release) event.
    /// </param>
    /// <returns>
    ///     <c>true</c> if the input was successfully sent to the system;
    ///     otherwise, <c>false</c>.
    /// </returns>
    /// <remarks>
    ///     This method uses scan codes instead of virtual‑key codes to avoid
    ///     issues with extended keys (e.g., right Alt, right Ctrl). The
    ///     system's extra info is automatically filled via
    ///     <see cref="GetMessageExtraInfo"/>.
    /// </remarks>
    public static Boolean SendKey(Keys key, Boolean keyDown)
    {
        INPUT[] inputs =
        [
            new INPUT
            {
                type = INPUT_KEYBOARD,
                ki = new KEYBDINPUT()
                {
                    // Setting wVk to 0 and using the scan code avoids issues with extended keys.
                    wVk = 0,
                    wScan = (UInt16)MapVirtualKey((UInt32)key, MAPVK_VK_TO_VSC),
                    dwFlags = (keyDown ? KEYEVENTF_KEYDOWN : KEYEVENTF_KEYUP) | KEYEVENTF_SCANCODE,
                    dwExtraInfo = GetMessageExtraInfo(),
                    time = 0 // Let the system provide the timestamp.
                }
            }
        ];

        // Send the input and return whether it was successfully queued.
        return SendInput(1, inputs, Marshal.SizeOf<INPUT>()) == 1;
    }

    #endregion
}